import {FormEvent, useEffect, useState} from 'react';
import {Check, ChevronRight, Clock3, Ellipsis, HandHeart, Info, Pencil, Plus, Search, Send, ShieldCheck, UserPlus, UsersRound, X} from 'lucide-react';
import {Link, useNavigate} from 'react-router-dom';
import {api} from '../../api/client';
import {EmptyState, ErrorState, LoadingPage, PageHeader, Tag, TrustBadge} from '../ui';

type VerificationStatus = 'verified' | 'unverified' | 'needs_review';
type Contact = {id: number; name: string; phone_number: string; relationship: string; nickname?: string | null; notes?: string | null; verification_status: VerificationStatus; verified_at?: string | null; created_at: string; last_interaction?: string | null; last_transfer_amount?: number | null; last_transfer_date?: string | null; total_transfers: number; total_requests: number; first_interaction?: string | null; activity?: Array<{kind: 'sent'|'requested'; label: string; amount: number; created_at: string}>};
type Helper = {id: number; helper_name: string; relationship: string; phone: string; status: 'pending'|'active'|'revoked'|'expired'; permissions: string[]; accepted_at?: string | null; last_activity?: Activity | null};
type Activity = {id?: number; event_type: string; detail?: string | null; created_at: string};
type AssistanceRequest = {id: number; helper_name: string; title: string; detail?: string | null; status: string};
const permissionGroups: Array<{title: string; items: Array<[string, string]>}> = [
  {title: 'Guidance', items: [['explain_financial_info', 'Explain financial information'], ['guide_navigation', 'Guide through app screens']]},
  {title: 'Visibility', items: [['view_alerts', 'View selected alerts'], ['view_financial_health', 'View financial health'], ['view_spending_summary', 'View spending summaries'], ['view_savings_goals', 'View savings goals'], ['view_budget_summary', 'View budget summary']]},
  {title: 'Transaction support', items: [['view_pending_transactions', 'View selected pending transactions'], ['prepare_transaction', 'Help prepare a transaction']]},
] ;
const permissionLabels = Object.fromEntries(permissionGroups.flatMap((group) => group.items));

function initials(name: string) { return name.split(' ').map((word) => word[0]).join('').slice(0, 2); }
function maskedPhone(phone: string) { return phone.length > 5 ? `${phone.slice(0, 3)}••••••${phone.slice(-2)}` : 'Hidden number'; }
function shortDate(value?: string | null) { return value ? new Intl.DateTimeFormat('en-BD', {month: 'short', day: 'numeric', year: 'numeric'}).format(new Date(value)) : ''; }
function statusText(status: VerificationStatus) { return status === 'verified' ? 'Verified' : status === 'needs_review' ? 'Review contact' : 'Needs verification'; }

export function ContactsPage() {
  const [contacts, setContacts] = useState<Contact[]>();
  const [error, setError] = useState('');
  const [adding, setAdding] = useState(false);
  const [editing, setEditing] = useState<Contact | null>(null);
  const [detail, setDetail] = useState<Contact | null>(null);
  const [removing, setRemoving] = useState<Contact | null>(null);
  const [requesting, setRequesting] = useState<Contact | null>(null);
  const [verify, setVerify] = useState<Contact | null>(null);
  const [menu, setMenu] = useState<number | null>(null);
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all'|'verified'|'unverified'|'recent'>('all');
  const navigate = useNavigate();
  const [notice, setNotice] = useState('');
  const load = () => { setError(''); void api<{items: Contact[]}>('/trusted-people').then((data) => setContacts(data.items)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load contacts.')); };
  useEffect(load, []);
  const openDetails = (contact: Contact) => { setMenu(null); void api<Contact>(`/trusted-people/${contact.id}`).then(setDetail).catch((reason: unknown) => setNotice(reason instanceof Error ? reason.message : 'Could not load person details.')); };
  const startSend = (contact: Contact) => { void api<Contact>(`/trusted-people/${contact.id}`).then((person) => navigate('/coach/assistant', {state: {trustedPayment: {id:person.id,name:person.name,phone:person.phone_number,relationship:person.relationship,verification_status:person.verification_status,last_transfer_amount:person.last_transfer_amount,last_transfer_date:person.last_transfer_date}}})).catch((reason: unknown) => setNotice(reason instanceof Error ? reason.message : 'Could not prepare this recipient.')); };
  const beginVerify = (contact: Contact) => { setMenu(null); void api<Contact>(`/trusted-people/${contact.id}`).then(setVerify).catch((reason: unknown) => setNotice(reason instanceof Error ? reason.message : 'Could not load this person’s details.')); };
  const beginEdit = (contact: Contact) => { setMenu(null); void api<Contact>(`/trusted-people/${contact.id}`).then(setEditing).catch((reason: unknown) => setNotice(reason instanceof Error ? reason.message : 'Could not load this person’s details.')); };
  const remove = async () => { if (!removing) return; try {await api(`/trusted-people/${removing.id}`, {method: 'DELETE'}); setRemoving(null); setDetail(null); setNotice('Person removed from Trusted People. Past activity is unchanged.'); load();} catch (reason) {setNotice(reason instanceof Error ? reason.message : 'Could not remove this person.');} };
  const confirmDetails = async () => {if (!verify) return; try {await api(`/trusted-people/${verify.id}/verify`, {method: 'POST'}); setVerify(null); setNotice('Details confirmed. This contact is now verified by you.'); load(); if (detail?.id === verify.id) openDetails(verify);} catch (reason) {setNotice(reason instanceof Error ? reason.message : 'Could not verify this person.');}};
  const visible = (contacts || []).filter((contact) => {const needle=query.trim().toLowerCase(); const matches=!needle || [contact.name,contact.phone_number,contact.relationship,contact.nickname || ''].some((value) => value.toLowerCase().includes(needle)); return matches && (filter === 'all' || (filter === 'recent' ? Boolean(contact.last_interaction) : contact.verification_status === filter));});
  if (error) return <ErrorState message={error} retry={load} />;
  return <div className="page people-page" onClick={() => setMenu(null)}>
    <PageHeader title="Trusted People" description="Save the people you know and get more context before sending money." action={<button className="button" onClick={() => setAdding(true)}><UserPlus />Add person</button>} />
    <section className="people-hero"><Info /><div><h2>Safer payments</h2><p>Recognize who you’re paying and review your history before you send. You always confirm every payment.</p></div></section>
    {notice && <div className="toast" role="status"><Check />{notice}</div>}
    {!contacts ? <PeopleSkeleton /> : contacts.length ? <><div className="people-toolbar"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search people…" /></label><div className="people-filters" role="group" aria-label="Filter people">{([['all','All'],['verified','Verified'],['unverified','Needs verification'],['recent','Recent']] as const).map(([value,label]) => <button className={filter === value ? 'active' : ''} onClick={(event) => {event.stopPropagation(); setFilter(value);}} key={value}>{label}</button>)}</div></div><div className="contacts-grid">{visible.map((contact) => <ContactCard key={contact.id} contact={contact} open={() => openDetails(contact)} send={() => startSend(contact)} request={() => setRequesting(contact)} menu={menu === contact.id} setMenu={() => setMenu(menu === contact.id ? null : contact.id)} edit={() => beginEdit(contact)} verify={() => beginVerify(contact)} remove={() => {setMenu(null); setRemoving(contact);}} />)}</div>{!visible.length && <EmptyState title="No people match your search" description="Try another name, number, or relationship." />}</> : <div className="people-empty"><UsersRound /><h2>No trusted people yet</h2><p>Save people you regularly send money to so you can recognize them and review their details more easily.</p><button className="button" onClick={() => setAdding(true)}><Plus />Add your first person</button><small>Family · Landlord · Friends · Regular service providers</small></div>}
    {adding && <ContactForm close={() => setAdding(false)} done={(message) => {setAdding(false); setNotice(message); load();}} />}
    {editing && <ContactForm contact={editing} close={() => setEditing(null)} done={(message) => {setEditing(null); setNotice(message); load();}} />}
    {detail && <ContactDetail contact={detail} close={() => setDetail(null)} send={() => startSend(detail)} request={() => setRequesting(detail)} edit={() => {setDetail(null); beginEdit(detail);}} verify={() => beginVerify(detail)} remove={() => setRemoving(detail)} />}
    {verify && <ConfirmDialog title={`Verify ${verify.name}'s details?`} text={`You are confirming ${verify.name}, ${verify.relationship}, and ${verify.phone_number}. This means verified by you — not identity or telecom verification.`} confirm="Confirm details" onClose={() => setVerify(null)} onConfirm={() => void confirmDetails()} />}
    {removing && <ConfirmDialog danger title={`Remove ${removing.name}?`} text="This removes the saved contact from Trusted People. It will not delete your past transactions or requests." confirm="Remove person" onClose={() => setRemoving(null)} onConfirm={() => void remove()} />}
    {requesting && <RequestMoneyDialog contact={requesting} close={() => setRequesting(null)} done={(message) => {setRequesting(null); setNotice(message); load();}} />}
  </div>;
}

function ContactCard({contact,open,send,request,menu,setMenu,edit,verify,remove}: {contact: Contact; open: () => void; send: () => void; request: () => void; menu: boolean; setMenu: () => void; edit: () => void; verify: () => void; remove: () => void}) { return <article className="contact-card"><button className="contact-card__body" onClick={open} aria-label={`View ${contact.name}`}><div className="contact-card__top"><span className="contact-avatar">{initials(contact.name)}</span><StatusBadge status={contact.verification_status} /></div><h2>{contact.name}</h2><p className="contact-card__relationship">{contact.relationship}</p><p className="contact-phone">{contact.phone_number}</p><div className="contact-card__context"><span>Last activity</span><strong>{contact.last_transfer_amount ? `৳${contact.last_transfer_amount.toLocaleString()} · ${shortDate(contact.last_transfer_date)}` : contact.total_requests ? `Requested money · ${shortDate(contact.last_interaction)}` : 'No transfers yet'}</strong></div></button><div className="contact-card__actions"><button className="button" onClick={send}><Send />Send money</button><button className="button button--secondary" onClick={request}>Request</button><div className="contact-menu"><button className="icon-button" aria-label={`More actions for ${contact.name}`} aria-expanded={menu} onClick={(event) => {event.stopPropagation(); setMenu();}}><Ellipsis /></button>{menu && <div role="menu"><button onClick={open}>View details</button><button onClick={edit}><Pencil />Edit person</button>{contact.verification_status !== 'verified' && <button onClick={verify}><ShieldCheck />Verify details</button>}<button className="danger" onClick={remove}>Remove</button></div>}</div></div></article>; }
function StatusBadge({status}: {status: VerificationStatus}) {return <span className={`contact-status contact-status--${status}`}><ShieldCheck />{statusText(status)}</span>;}
function PeopleSkeleton() {return <><div className="people-toolbar people-toolbar--loading" /><div className="contacts-grid">{[1,2,3].map((id) => <div className="contact-skeleton" key={id}><i /><i /><i /></div>)}</div></>;}
function ContactForm({contact, close, done}: {contact?: Contact; close: () => void; done: (message: string) => void}) {
  const [name, setName] = useState(contact?.name || ''); const [phone, setPhone] = useState(contact?.phone_number || ''); const [relationship, setRelationship] = useState(contact?.relationship || ''); const [nickname, setNickname] = useState(contact?.nickname || ''); const [notes, setNotes] = useState(contact?.notes || ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try {const body={name,phone_number:phone,relationship,nickname:nickname || null,notes:notes || null}; await api(contact ? `/trusted-people/${contact.id}` : '/trusted-people', {method: contact ? 'PUT' : 'POST', body: JSON.stringify(body)}); done(contact && phone !== contact.phone_number ? 'Person updated. Verify the changed number before your next transfer.' : contact ? 'Person updated.' : 'Contact added. Verify the number before your first transfer.');} catch (reason) {setError(reason instanceof Error ? reason.message : 'Could not save this person.');} finally {setSaving(false);} };
  return <div className="backdrop" onMouseDown={close}><form className="people-form" onSubmit={(event) => void submit(event)} onMouseDown={(event) => event.stopPropagation()}><div className="sheet__header"><div><span className="eyebrow">Trusted People</span><h2>{contact ? 'Edit person' : 'Add a person'}</h2></div><button className="icon-button" onClick={close} type="button" aria-label="Close"><X /></button></div><p>Saved contacts are not automatically safe. Confirm their details before sending money.</p><label className="field"><span>Name</span><input required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Mobile number</span><input required inputMode="tel" placeholder="01812345678" value={phone} onChange={(event) => setPhone(event.target.value)} /></label><label className="field"><span>Relationship</span><select required value={relationship} onChange={(event) => setRelationship(event.target.value)}><option value="">Choose relationship</option>{['Parent','Child','Sibling','Spouse','Relative','Friend','Landlord','Colleague','Merchant / Service','Other'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="field"><span>Nickname <small>Optional</small></span><input value={nickname} maxLength={40} onChange={(event) => setNickname(event.target.value)} /></label><label className="field"><span>Notes <small>Optional — no secrets</small></span><textarea value={notes} maxLength={280} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<div className="wizard-actions"><button className="button button--ghost" type="button" onClick={close}>Cancel</button><button className="button" disabled={saving}>{saving ? 'Saving…' : contact ? 'Save changes' : 'Save person'}</button></div></form></div>;
}
function ContactDetail({contact,close,send,request,edit,verify,remove}: {contact: Contact; close: () => void; send: () => void; request: () => void; edit: () => void; verify: () => void; remove: () => void}) {return <div className="backdrop" onMouseDown={close}><section className="sheet people-detail" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><div className="sheet__header"><div><span className="contact-avatar">{initials(contact.name)}</span><h2>{contact.name}</h2><p>{contact.relationship} · {contact.phone_number}</p></div><button className="icon-button" onClick={close}><X /></button></div><div className="people-detail__body"><StatusBadge status={contact.verification_status} /><p className="people-detail__description">{contact.verification_status === 'verified' ? 'You confirmed this person’s saved details.' : 'Check the saved number before sending money.'}</p><small>Added {shortDate(contact.created_at)}</small><div className="people-detail__actions"><button className="button" onClick={send}><Send />Send money</button><button className="button button--secondary" onClick={request}>Request</button></div><section><h3>Recent activity</h3>{contact.activity?.length ? <ol className="contact-activity">{contact.activity.map((row,index) => <li key={`${row.created_at}-${index}`}><span>{row.label}</span><strong>৳{row.amount.toLocaleString()}</strong><small>{shortDate(row.created_at)}</small></li>)}</ol> : <p className="quiet">No interactions yet. Verify the recipient carefully before the first transfer.</p>}</section><section className="people-summary"><h3>Summary</h3><div><span><strong>{contact.total_transfers}</strong>Transfers sent</span><span><strong>{contact.total_requests}</strong>Requests</span><span><strong>{contact.last_interaction ? shortDate(contact.last_interaction) : '—'}</strong>Last interaction</span></div></section><div className="people-detail__footer"><button className="button button--secondary" onClick={edit}><Pencil />Edit person</button>{contact.verification_status !== 'verified' && <button className="text-button" onClick={verify}>Verify details</button>}<button className="text-button danger" onClick={remove}>Remove from Trusted People</button></div></div></section></div>;}
function ConfirmDialog({title,text,confirm,onClose,onConfirm,danger=false}: {title:string;text:string;confirm:string;onClose:()=>void;onConfirm:()=>void;danger?:boolean}) {return <div className="backdrop" onMouseDown={onClose}><section className="people-form revoke-dialog" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><div className="sheet__header"><h2>{title}</h2><button className="icon-button" onClick={onClose}><X /></button></div><p>{text}</p><div className="wizard-actions"><button className="button button--ghost" onClick={onClose}>Cancel</button><button className={`button ${danger ? 'button--danger' : ''}`} onClick={onConfirm}>{confirm}</button></div></section></div>;}
function RequestMoneyDialog({contact,close,done}: {contact: Contact;close:()=>void;done:(message:string)=>void}) {const [amount,setAmount]=useState('');const [note,setNote]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try {await api(`/trusted-people/${contact.id}/request`,{method:'POST',body:JSON.stringify({amount:Number(amount),note:note || null})});done(`Request sent to ${contact.name}.`);} catch(reason) {setError(reason instanceof Error ? reason.message : 'Could not create this request.');} finally {setSaving(false);}};return <div className="backdrop" onMouseDown={close}><form className="people-form" onSubmit={(event)=>void submit(event)} onMouseDown={(event)=>event.stopPropagation()}><div className="sheet__header"><div><span className="eyebrow">Request money</span><h2>Request from {contact.name}</h2></div><button className="icon-button" type="button" onClick={close}><X /></button></div><p>This records a payment request. It does not move money or mark it paid.</p><label className="field"><span>Amount</span><input required min="1" type="number" inputMode="decimal" value={amount} onChange={(event)=>setAmount(event.target.value)} /></label><label className="field"><span>Note <small>Optional</small></span><input maxLength={140} value={note} onChange={(event)=>setNote(event.target.value)} placeholder="For example: October rent" /></label>{error && <p className="form-error">{error}</p>}<div className="wizard-actions"><button className="button button--ghost" type="button" onClick={close}>Cancel</button><button className="button" disabled={saving}>{saving ? 'Creating…' : 'Create request'}</button></div></form></div>;}

export function TrustedHelperPage() {
  const [helpers, setHelpers] = useState<Helper[]>(); const [activities, setActivities] = useState<Activity[]>([]); const [requests, setRequests] = useState<AssistanceRequest[]>([]); const [error, setError] = useState(''); const [adding, setAdding] = useState(false); const [managing, setManaging] = useState<Helper | null>(null); const [revoking, setRevoking] = useState<Helper | null>(null); const [notice, setNotice] = useState('');
  const load = () => {setError(''); void Promise.all([api<{items: Helper[]}>('/trusted-helpers'), api<{items: Activity[]}>('/helper-activity'), api<{items: AssistanceRequest[]}>('/helper-requests')]).then(([h, a, r]) => {setHelpers(h.items); setActivities(a.items); setRequests(r.items);}).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load Helper Mode.'));};
  useEffect(load, []);
  const revoke = async () => {if (!revoking) return; try {await api(`/trusted-helpers/${revoking.id}/revoke`, {method: 'POST'}); setNotice(`Access revoked for ${revoking.helper_name}.`); setRevoking(null); load();} catch (reason) {setNotice(reason instanceof Error ? reason.message : 'Could not revoke access.');}};
  const review = async (request: AssistanceRequest) => {try {await api(`/helper-requests/${request.id}/review`, {method: 'POST', body: JSON.stringify({decision: 'approved'})}); setNotice('Request reviewed. You still confirm any payment with your PIN.'); load();} catch (reason) {setNotice(reason instanceof Error ? reason.message : 'Could not review request.');}};
  if (error) return <ErrorState message={error} retry={load} />;
  if (!helpers) return <LoadingPage label="Loading Helper Mode" />;
  return <div className="page helper-dashboard"><PageHeader title="Helper Mode" description="Let someone you trust guide you without giving them control of your money." action={<button className="button" onClick={() => setAdding(true)}><Plus />Add helper</button>} />
    <section className="helper-control-note"><ShieldCheck /><span><strong>You always stay in control.</strong> Helpers can only access the permissions you approve.</span><Tag tone="positive">Protected assistance</Tag></section>
    {notice && <div className="toast" role="status"><Check />{notice}</div>}
    <section><div className="helper-section-title"><div><h2>Trusted helpers</h2><p>Manage exactly what each person can see and do.</p></div></div>{helpers.length ? <div className="helper-list">{helpers.map((helper) => <HelperCard key={helper.id} helper={helper} manage={() => setManaging(helper)} revoke={() => setRevoking(helper)} />)}</div> : <div className="helper-empty"><HandHeart /><div><h2>No trusted helpers yet</h2><p>Add someone you trust to help explain information and navigate the app when needed.</p><button className="button" onClick={() => setAdding(true)}><Plus />Add your first helper</button></div></div>}</section>
    {requests.length > 0 && <section className="helper-section"><div className="helper-section-title"><div><h2>Needs your confirmation</h2><p>A helper can prepare or explain; only you can approve the final action.</p></div></div><div className="helper-requests">{requests.map((request) => <article key={request.id}><span className="helper-request__icon"><HandHeart /></span><div><strong>{request.helper_name} prepared: {request.title}</strong><p>{request.detail || 'Waiting for your confirmation'}</p><small>Prepared with help — payment is not sent.</small></div><button className="button button--secondary" onClick={() => void review(request)}>Review <ChevronRight /></button></article>)}</div></section>}
    <section className="helper-section helper-layout"><div className="helper-activity"><div className="helper-section-title"><div><h2>Recent activity</h2><p>See what changed and what your helpers viewed.</p></div></div>{activities.length ? <ol>{activities.slice(0, 6).map((activity, index) => <li key={activity.id || index}><span><Clock3 /></span><div><strong>{activity.detail || activity.event_type.replace(/_/g, ' ')}</strong><small>{new Date(activity.created_at).toLocaleString()}</small></div></li>)}</ol> : <p className="helper-muted">Activity will appear here when you invite a helper or change access.</p>}</div><PrivacyCard /></section>
    {adding && <HelperEditor close={() => setAdding(false)} done={(message) => {setAdding(false); setNotice(message); load();}} />}
    {managing && <HelperEditor helper={managing} close={() => setManaging(null)} done={(message) => {setManaging(null); setNotice(message); load();}} />}
    {revoking && <div className="backdrop" onMouseDown={() => setRevoking(null)}><section className="people-form revoke-dialog" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><div className="sheet__header"><div><span className="eyebrow">Remove access</span><h2>Revoke access for {revoking.helper_name}?</h2></div><button className="icon-button" onClick={() => setRevoking(null)}><X /></button></div><p>They will no longer be able to view or assist with your account. Your financial data will remain unchanged.</p><div className="wizard-actions"><button className="button button--ghost" onClick={() => setRevoking(null)}>Cancel</button><button className="button button--danger" onClick={() => void revoke()}>Revoke access</button></div></section></div>}
  </div>;
}

function HelperCard({helper, manage, revoke}: {helper: Helper; manage: () => void; revoke: () => void}) {
  const shown = helper.permissions.slice(0, 3); const remaining = helper.permissions.length - shown.length;
  return <article className="helper-card"><div className="helper-card__identity"><span className="contact-avatar">{initials(helper.helper_name)}</span><div><div className="helper-card__name"><h3>{helper.helper_name}</h3><Status status={helper.status} /></div><p>{helper.relationship} · {maskedPhone(helper.phone)}</p></div></div><div className="helper-card__body"><span className="helper-label">Permissions</span><div className="helper-permissions">{shown.map((permission) => <span key={permission}>{permissionLabels[permission] || permission}</span>)}{remaining > 0 && <span>+{remaining} more</span>}</div>{helper.last_activity && <p className="helper-last">Last activity: {helper.last_activity.detail || helper.last_activity.event_type.replace(/_/g, ' ')}</p>}</div><div className="helper-card__actions"><button className="button button--secondary" onClick={manage} disabled={helper.status === 'revoked'}>Manage access</button>{helper.status !== 'revoked' && <button className="text-button helper-revoke" onClick={revoke}>Revoke access</button>}</div></article>;
}

function Status({status}: {status: Helper['status']}) {return <span className={`helper-status helper-status--${status}`}>{status === 'pending' ? 'Invitation pending' : status[0].toUpperCase() + status.slice(1)}</span>;}

function PrivacyCard() {return <aside className="helper-privacy"><ShieldCheck /><div><h2>What helpers can never do</h2><ul><li>See your PIN or OTP</li><li>Confirm payments for you</li><li>Send money without your approval</li><li>Change security settings</li><li>Access permissions you did not grant</li></ul></div></aside>;}

function HelperEditor({helper, close, done}: {helper?: Helper; close: () => void; done: (message: string) => void}) {
  const [name, setName] = useState(helper?.helper_name || ''); const [phone, setPhone] = useState(helper?.phone || ''); const [relationship, setRelationship] = useState(helper?.relationship || ''); const [permissions, setPermissions] = useState<string[]>(helper?.permissions || ['explain_financial_info', 'guide_navigation', 'view_alerts']); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const toggle = (permission: string) => setPermissions((current) => current.includes(permission) ? current.filter((item) => item !== permission) : [...current, permission]);
  const submit = async (event: FormEvent) => {event.preventDefault(); setError(''); if (!permissions.length) {setError('Choose at least one permission.'); return;} setSaving(true); try {if (helper) await api(`/trusted-helpers/${helper.id}/permissions`, {method: 'PUT', body: JSON.stringify({permissions})}); else await api('/trusted-helpers', {method: 'POST', body: JSON.stringify({helper_name: name, phone, relationship, permissions})}); done(helper ? 'Permissions updated.' : 'Invitation sent. It will remain pending until accepted.');} catch (reason) {setError(reason instanceof Error ? reason.message : 'Could not save helper settings.');} finally {setSaving(false);}};
  return <div className="backdrop" onMouseDown={close}><form className="people-form helper-editor" onSubmit={(event) => void submit(event)} onMouseDown={(event) => event.stopPropagation()}><div className="sheet__header"><div><span className="eyebrow">{helper ? 'Access settings' : 'Protected assistance'}</span><h2>{helper ? `Manage ${helper.helper_name}` : 'Add trusted helper'}</h2></div><button className="icon-button" onClick={close} type="button" aria-label="Close"><X /></button></div>{!helper && <><p>Who is helping you?</p><label className="field"><span>Helper name</span><input required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Mobile number</span><input required inputMode="tel" placeholder="018XXXXXXXX" value={phone} onChange={(event) => setPhone(event.target.value)} /></label><label className="field"><span>Relationship</span><select required value={relationship} onChange={(event) => setRelationship(event.target.value)}><option value="">Choose relationship</option>{['Parent','Child','Sibling','Spouse','Relative','Friend','Caregiver','Other'].map((item) => <option key={item}>{item}</option>)}</select></label></>}<h3 className="helper-editor__heading">Choose what they can access</h3>{permissionGroups.map((group) => <fieldset className="helper-permission-group" key={group.title}><legend>{group.title}</legend>{group.items.map(([key, label]) => <label key={key} className="permission-toggle"><input type="checkbox" checked={permissions.includes(key)} onChange={() => toggle(key)} />{label}</label>)}</fieldset>)}<div className="permission-lock"><ShieldCheck />Helpers can never see your PIN or OTP, confirm payments, send money, or change security settings.</div>{error && <p className="form-error">{error}</p>}<div className="wizard-actions"><button className="button button--ghost" type="button" onClick={close}>Cancel</button><button className="button" disabled={saving}>{saving ? 'Saving…' : helper ? 'Save changes' : 'Send invitation'}</button></div></form></div>;
}
